### PR TITLE
Refactored into more modularised code 

### PR DESCRIPTION
**Pull request by macaullyjames**
Hi there :)

I've spent some time refactoring the code to make it easier to maintain and develop, since it was quite tightly coupled before. Basically, every angular module, directive, service etc. has been encapsulated in a CommonJS module. Inter-module dependencies are done by `require`-ing á la node with the help of [browserify](http://browserify.org).

What this means is that there isn't any global state between components anymore, which in turn means that we can start poking at individual parts (like the providers, for example) without worrying about breaking other parts of the code. Yay! :)

This is a big PR (44 commits), but in summary:
- **Split up the codebase into CommonJS modules, stitched together with Browserify**
- **Stopped using Bower**  
  Since npm can do everything we need by itself.
- **Removed the tests**  
  Since they didn't really test that much, and we can start writing proper unit tests now that the code is more modular (before, the entire library was loaded).
- **Moved from Grunt to Gulp for building**  
  This made the build process much more concise and understandable.
- **Replaced some code in `utils.js` with npm modules**  
  Less code to maintain is better.

The examples (in `examples/`) that worked _before_ refactoring (not all of them did) work as before. As for regressions, there are only two that I can think of:
- **Uglification/minification has been (temporarily) taken out of the build process**  
  The tooling was causing headaches with source maps, but this shouldn't be too hard to fix.
- **Dependencies (angular, underscore etc.) are always bundled**  
  There is no build that doesn't bundle the dependencies into the `endev.js` file. This shouldn't be too hard to fix either, it's just a matter of creating a separate build.

I've created the `develop` branch since I'm not sure this is prime for `master` yet. Once you've cloned the PR, run

```
git clean -fdx
npm install
npm run build
```

to clean out the old bower files etc., install the new dependencies and build the library. This will put `endev.full.js` in the `dist/` folder.

Enjoy! :)

### CODE REVIEW

**Comment by filipkis** [comment]
Nice work.

I'll review the code in details a bit later, but just one quick comment, I want to keep the bower.json so that it can be installed via bower. npm is meant for server side installations, while bower is meant for clientside, so it's good to have it as well.

**Comment by macaullyjames** [comment]
Ah, I didn't think of needing Bower for _publishing_. I'll restore the bower.json then :)

**Comment by macaullyjames** [comment]
Fixed, now you can `bower` to your heart's content :)

**Comment by macaullyjames** [comment]
OT: Now that I think about it, it would be cool to have Gulp take care of publishing as well; `gulp publish` could automatically bump the version number and publish to bower/npm :)

**Comment by macaullyjames** [comment]
As per the discussion in #3, I've merged this to continue development.

**Pull request merged**
